# Generated by Django 4.2.20 on 2025-03-19 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='project title', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Task title', max_length=255)),
                ('description', models.CharField(default='description', max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'Inprogress'), ('New', 'New')], default='New', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focusflow.project')),
            ],
        ),
    ]
